/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_embsky_Hello */

#ifndef _Included_com_embsky_Hello
#define _Included_com_embsky_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_embsky_Hello
 * Method:    selectChannel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_embsky_Hello_selectChannel
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
